services:
  - type: web
    name: goldgem-ai
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    env: python
    plan: free
    region: oregon
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: PORT
        value: "10000"
